# Generated by Django 2.0.9 on 2019-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidVersion',
            fields=[
                ('version', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to='apks', verbose_name='apk地址')),
            ],
            options={
                'verbose_name': '安卓app更新',
                'verbose_name_plural': '安卓app更新',
            },
        ),
    ]
