# Generated by Django 2.0.9 on 2019-04-04 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_auth',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_data', models.TextField(verbose_name='Token保存的缓存数据')),
                ('expire_date', models.DateTimeField(null=True, verbose_name='有效期到')),
            ],
            options={
                'verbose_name': 'Api授权有效期',
                'verbose_name_plural': 'Api授权有效期',
            },
        ),
    ]
