# Generated by Django 2.0.9 on 2019-04-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('material', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bind_store', to='store.Store', verbose_name='绑定项目'),
        ),
        migrations.AddField(
            model_name='bussinessmats',
            name='bussiness',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bussiness_customer', to='customer.Customer', verbose_name='签约企业'),
        ),
        migrations.AddField(
            model_name='bussinessmats',
            name='material',
            field=models.ManyToManyField(db_constraint=False, null=True, related_name='bussiness_bind_store_material', to='material.Material', verbose_name='签约商品'),
        ),
        migrations.AddField(
            model_name='bussinessmats',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bussiness_bind_store', to='store.Store', verbose_name='签约项目'),
        ),
        migrations.AddField(
            model_name='buesinessapply',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='buesiness_apply', to='customer.Customer', verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='buesinessapply',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_store', to='store.Store', verbose_name='签约项目'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='customer.Customer', verbose_name='用户'),
        ),
    ]
