# Generated by Django 2.0.9 on 2019-04-03 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustromerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='用户')),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, verbose_name='角色名')),
                ('subsidy', models.FloatField(default=0, verbose_name='角色补贴')),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='所属用户')),
            ],
            options={
                'ordering': ('customer',),
            },
        ),
        migrations.AddField(
            model_name='custromerrole',
            name='role',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='custrole.Role', verbose_name='角色'),
        ),
    ]
