# Generated by Django 2.0.9 on 2019-04-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField(default=1, verbose_name='数量')),
                ('material', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='material.Material', verbose_name='商品')),
                ('quote', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='quote.Quote', verbose_name='购物车')),
            ],
            options={
                'verbose_name': '购物车明细',
                'verbose_name_plural': '购物车明细',
            },
        ),
    ]
