import sys
"""
Django settings for foods project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 设置Apps的默认路径为apps
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
# 设置xadmin及相关功能的路径为 django_extra
sys.path.insert(0, os.path.join(BASE_DIR, 'django_extra'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w6cbip#1p=638&a&8@-0m2y!ls-1e_(t9p$i_%loox6j=t92dy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', ]


# Application definition

INSTALLED_APPS = [
    'django_crontab',  # 计划任务
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',  # Xadmin后台管理框架
    'crispy_forms',  # Xadmin后台管理框架所需内容
    'reversion',  # Xadmin后台管理框架所需内容
    'DjangoUeditor',  # 富文本编辑框
    'easy_thumbnails',  # 图片压缩
    'rest_framework',  # reset_framework API框架
    'rest_framework_swagger',  # Swagger自动API文档工具
    'django_filters',  # django 过滤
    'corsheaders',  # 跨域问题解决方案
    'system',  # 后台展示的配置
    'customer',  # 用户APP
    'sms',  # 短信管理APP
    'material',  # 菜品管理APP
    'order',  # 订单APP
    'store',  # 项目记录
    'quote',  # 购物车
    'api',  # API类
    'weixinpay',  # 微信网页支付
    'autoupgrade',  # 升级apk
    'custrole',  # 用户角色
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 跨域问题解决方案
    'django.middleware.common.CommonMiddleware',  # 跨域问题解决方案
]

ROOT_URLCONF = 'foods.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'foods.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'foods',
        'USER': 'root',
        'PASSWORD': '3sricheS',
        'HOST': '192.168.0.200',
        # 'HOST': '19521p40y6.iok.la',
        # 'NAME': 'foods',
        # 'USER': 'service',
        # 'PASSWORD': 'Jiejfi!@#$jfi1(',
        # 'HOST': '112.74.171.153',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 重载用户model
AUTH_USER_MODEL = 'system.User'

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
# 使用这种方法设置静态文件的路径,否则在Linux上会路径出错
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_DIRS = (
# os.path.join(BASE_DIR, 'static'),
# )

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}

TOKEN_EXPIRE = 0  # TOKEN的有效期,0为不过期,单位:分钟

# 上传图片默认路径
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media/')
MEDIA_URL = '/static/media/'


CORS_ORIGIN_ALLOW_ALL = True  # 设置允许所有域名 该配置为True无法设置cookie

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    'localhost:8000',
    '127.0.0.1:5500',
)  # 可以跨域的域名白名单

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

# CORS_ORIGIN_REGEX_WHITELIST = () #跨域域名正则表达式白名单

# CORS_URLS_REGEX = r'^/api/.*$' #允许跨域的ULR正则表达式

# 高德地图开放平台API
MAP_KEY = 'ff96a70d9e4f0be17dd4bcad4409b1db'

# 日志中显示SQL
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console':{
#             'level':'DEBUG',
#             'class':'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'propagate': True,
#             'level':'DEBUG',
#         },
#     }
# }

# 短信验证码设置
SMSCAPTCHA = {
    'LENGTH': 4,  # 验证码长度
    'EXPIRE': 10,  # 验证码有效期,单位分钟
    'TEMPLATE': 'TP18093014',  # 验证码短信模板ID
}

GAODEMAP_KEY = '79dd5e6ba6351a98641ef1e5a6a01e8d'
GAODEMAP_URL = 'http://webapi.amap.com/maps?v=1.4.6'

CRONJOBS = [
    ('*/5 * * * *', 'syssetting.cront.checkOrderPaied'),
    ('* */1 * * *', 'syssetting.cront.autoCancelUnPaiedBooking',
     '>> /Apps/webs/foodsService/logs/autoCancelUnPaiedBooking.log'),
    ('0 * * * *', 'syssetting.cront.setBookingTimeOut',
     '>> /Apps/webs/foodsService/logs/setBookingTimeOut.log'),
    ('0 2 * * *', 'syssetting.cront.calcStatisticalEveryDay',
     '>> /Apps/webs/foodsService/logs/calcStatisticalEveryDay.log')
]

# 图片压缩
THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (200, 200), 'crop': True},
        'avatar_nocrop': {'size': (200, 200), 'crop': False},
        '64': {'size': (64, 64), 'crop': False},
        '128': {'size': (128, 128), 'crop': False},
        'big': {'size': (500, 500), 'crop': True},
        'big_nocrop': {'size': (500, 500), 'crop': False},
        'huge': {'size': (1000, 1000), 'crop': True},
        'huge_nocrop': {'size': (1000, 1000), 'crop': False},
    },
}
