# Generated by Django 2.0.9 on 2019-04-03 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('increment_id', models.CharField(default='', max_length=20, verbose_name='订单编号')),
                ('order_type', models.IntegerField(choices=[(0, '预定订单'), (1, '现场订单')], default=0, verbose_name='订单类型')),
                ('paied', models.BooleanField(default=False, verbose_name='是否付款')),
                ('paytype', models.CharField(choices=[('WeChat', '微信支付'), ('monthly', '月结')], default='WeChat', max_length=15, verbose_name='结算方式')),
                ('qty', models.IntegerField(default=0, verbose_name='订单总数')),
                ('amt', models.FloatField(default=0, verbose_name='订单总金额')),
                ('address_snapshot', models.CharField(blank=True, max_length=150, null=True, verbose_name='送餐地址快照')),
                ('status', models.CharField(choices=[('new', '新订单'), ('cancel', '已取消'), ('confirm', '已确认'), ('sending', '派送中'), ('complate', '已完成')], default='new', max_length=15, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('confirm_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='确认时间')),
                ('cancel_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='取消时间')),
                ('complate_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='完成时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付平台交易ID')),
                ('paied_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='支付时间')),
                ('prepayid', models.CharField(blank=True, max_length=100, null=True, verbose_name='预支付ID')),
                ('prepay_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='预支付时间')),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_customer_address', to='customer.Address', verbose_name='送货地址')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_customer', to='customer.Customer', verbose_name='下单客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=1, verbose_name='项次号')),
                ('status', models.CharField(choices=[('new', '待确认'), ('pick-up', '已取货'), ('confirm', '待取货'), ('timeout', '已超时'), ('rejected', '已驳回')], default='confirm', max_length=50, verbose_name='状态')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='预定的商品')),
                ('price', models.FloatField(default=0, verbose_name='菜品单价')),
                ('qty', models.IntegerField(default=0, verbose_name='数量')),
                ('amt', models.FloatField(default=0, verbose_name='小计')),
                ('mattype', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_mattype', to='material.MatType', verbose_name='商品类别')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
